/**
 * Constantes de compatibilidade.
 *
 * Fonte de verdade: `src/constants.ts`.
 */

import { MATERIAS, STORAGE_KEYS, STUDY } from '../constants';

export const APP_CONFIG = {
  TIMING: {
    POMODORO_FOCUS: STUDY.DEFAULT_POMODORO_MINUTES * 60,
    POMODORO_SHORT_BREAK: STUDY.DEFAULT_BREAK_MINUTES * 60,
    POMODORO_LONG_BREAK: 15 * 60,
    POMODORO_CYCLES_FOR_LONG: 4,
  },

  XP: {
    PER_MINUTE: STUDY.POINTS_PER_MINUTE,
    PER_LEVEL: 1000,
  },

  GOALS: {
    DAILY_GOAL_MINUTES: STUDY.DEFAULT_DAILY_GOAL_MINUTES,
    MIN_SESSION_MINUTES: 1,
  },

  STORAGE_KEYS: {
    USER: STORAGE_KEYS.USER,
    DATA_PREFIX: STORAGE_KEYS.DATA_PREFIX,
    THEME: STORAGE_KEYS.THEME,
    SESSION: STORAGE_KEYS.SESSION,
  },

  SUBJECTS: {
    ANATOMIA: MATERIAS[0],
    FISIOLOGIA: MATERIAS[1],
    FARMACOLOGIA: MATERIAS[2],
    PATOLOGIA: MATERIAS[3],
    BIOQUIMICA: MATERIAS[4],
    HISTOLOGIA: MATERIAS[5],
    OUTRA: MATERIAS[6],
  } as const,

  APP: {
    NAME: 'Zero Base',
    VERSION: '2.1.0',
  },
} as const;

export type Subject = (typeof APP_CONFIG.SUBJECTS)[keyof typeof APP_CONFIG.SUBJECTS];

